version: '3.8'
services:
    caloread-db:
        image: postgres
        restart: always
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: caloread
